// Copyright © 2026 & onwards, Alessandro Di Ronza <ales.drnz@gmail.com>.
// All rights reserved.
// Use of this source code is governed by BSD 3-Clause license that can be
// found in the LICENSE file.

@TestOn('mac-os || linux')
library;

import 'dart:io';

import 'package:test/test.dart';
import 'package:mpv_audio_kit/mpv_audio_kit.dart';
import '../_helpers/codec.dart';
import '../_helpers/libmpv_resolver.dart';

void main() {
  // The full codec matrix (18 fixtures, ~2 MB) lives in
  // `test/fixtures/codec/` and is regenerated by
  // `scripts/generate_codec_fixtures.sh`. The same matrix is exercised
  // on iOS / Android by `test_app/integration_test/codec_coverage_test.dart`
  // — that suite verifies the same expectations against the platform's
  // libmpv binary, while this one validates the host build (which is
  // the patched build under the maintainer's control).
  final fixturesDir = '${Directory.current.path}/test/fixtures/codec';

  setUpAll(() {
    final lib = resolveLibmpv();
    if (lib == null) {
      markTestSkipped('libmpv not found');
      return;
    }
    MpvAudioKit.ensureInitialized(libmpv: lib, hotRestartCleanup: false);
  });

  group('Codec coverage — host build', () {
    late Player player;

    setUpAll(() async {
      player = await createTestPlayer();
    });

    tearDownAll(() async {
      await player.stop();
      await player.dispose();
    });

    for (final entry in codecMatrix) {
      final filename = entry.$1;
      final expected = entry.$2;
      test(expected.label, () async {
        final path = '$fixturesDir/$filename';
        if (!File(path).existsSync()) {
          markTestSkipped('Fixture missing: run scripts/generate_codec_fixtures.sh');
          return;
        }
        final result = await verifyCodec(player, path, expected);

        expect(result.params.sampleRate, expected.sampleRate,
            reason: 'sample rate must match the fixture for ${expected.label}');
        expect(result.params.channelCount, expected.channels,
            reason: 'channel count must match the fixture for ${expected.label}');
        expect(result.duration.inMilliseconds, greaterThan(0),
            reason: 'duration must be reported by the demuxer');

        // Codec id varies between mpv builds (mp3 vs mp3float, aac vs aac_lc,
        // pcm_s16le vs pcm_s32le, etc.) and the short form lives in either
        // `codec` or `codecName` depending on the mpv version. We accept a
        // case-insensitive substring match against either field — enough to
        // catch a regression where the wrong decoder picked up the file.
        if (expected.codecHint != null) {
          final h = expected.codecHint!.toLowerCase();
          final c = (result.params.codec ?? '').toLowerCase();
          final cn = (result.params.codecName ?? '').toLowerCase();
          expect(
            c.contains(h) || cn.contains(h),
            isTrue,
            reason: 'codec id should contain "${expected.codecHint}" for '
                '${expected.label}; got codec="${result.params.codec}", '
                'codecName="${result.params.codecName}"',
          );
        }
      }, timeout: const Timeout(Duration(seconds: 30)));
    }
  });
}
