group = "com.example.mpv_audio_kit"
version = "1.0-SNAPSHOT"

buildscript {
    val kotlinVersion = "2.2.20"
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.7.2")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.21")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

plugins {
    id("com.android.library")
    id("kotlin-android")
}

android {
    namespace = "com.example.mpv_audio_kit"

    compileSdk = 36
    ndkVersion = "28.2.13676358"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    sourceSets {
        getByName("main") {
            java.srcDirs("src/main/kotlin")
        }
        getByName("test") {
            java.srcDirs("src/test/kotlin")
        }
    }

    defaultConfig {
        minSdk = 24

        // ── libmpv NDK ──────────────────────────────────────────────────────
        // Richiede i sorgenti/prebuilts di libmpv nelle seguenti ABI.
        // Strategie supportate:
        //   1. Prefab: npm run build (mpv-android) e importa come AAR
        //   2. Prebuilt SO: copia libmpv.so in
        //      android/src/main/jniLibs/<abi>/libmpv.so
        //   3. mpv-android: usa il gradle script ufficiale
        //
        // Per ora il plugin carica libmpv.so a runtime via dart:ffi.
        // Se le .so sono presenti in jniLibs vengono packagizzate nell'APK.
        ndk {
            abiFilters += listOf("arm64-v8a", "x86_64")
        }

        // Link CMakeLists per il wrapper JNI/NDK
        externalNativeBuild {
            cmake {
                cppFlags("")
                arguments("-DANDROID_STL=c++_shared")
            }
        }
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.22.1"
        }
    }

    testOptions {
        unitTests {
            isIncludeAndroidResources = true
            all {
                it.useJUnitPlatform()

                it.outputs.upToDateWhen { false }

                it.testLogging {
                    events("passed", "skipped", "failed", "standardOut", "standardError")
                    showStandardStreams = true
                }
            }
        }
    }
}

dependencies {
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.mockito:mockito-core:5.0.0")
}

import java.io.FileOutputStream
import java.net.URL
import java.security.MessageDigest

val MPV_RELEASE_VERSION = "v0.0.1"
val MPV_BASE_URL = "https://github.com/my-org/mpv_audio_kit/releases/download/\${MPV_RELEASE_VERSION}"

val downloadMpvTask = tasks.register("downloadMpvLibraries") {
    // Replace these SHA-256 hashes with the ones generated by scripts/generate_checksums.sh
    val abis = mapOf(
        "arm64-v8a" to mapOf(
            "file" to "libmpv_android-arm64-v8a.so",
            "sha256" to "PUT_ARM64_SHA256_HERE"
        ),
        "x86_64" to mapOf(
            "file" to "libmpv_android-x86_64.so",
            "sha256" to "PUT_X86_64_SHA256_HERE"
        )
    )
    
    doLast {
        val jniLibsDir = file("src/main/jniLibs")
        abis.forEach { (abi, info) ->
            val filename = info["file"]!!
            val expectedHash = info["sha256"]!!
            val abiDir = file("${jniLibsDir}/${abi}")
            if (!abiDir.exists()) abiDir.mkdirs()
            
            val targetFile = file("${abiDir}/libmpv.so")
            var isValid = false
            
            if (targetFile.exists()) {
                val bytes = targetFile.readBytes()
                val digest = MessageDigest.getInstance("SHA-256").digest(bytes)
                val calculatedHash = digest.joinToString("") { "%02x".format(it) }
                if (calculatedHash == expectedHash) {
                    isValid = true
                } else {
                    println("SHA-256 mismatch for ${abi}. Expected: ${expectedHash}, Got: ${calculatedHash}")
                    targetFile.delete()
                }
            }
            
            if (!isValid) {
                val url = "${MPV_BASE_URL}/${filename}"
                println("Downloading libmpv.so for ${abi} from ${url}")
                try {
                    URL(url).openStream().use { input ->
                        FileOutputStream(targetFile).use { output ->
                            input.copyTo(output)
                        }
                    }
                    val bytes = targetFile.readBytes()
                    val digest = MessageDigest.getInstance("SHA-256").digest(bytes)
                    val calculatedHash = digest.joinToString("") { "%02x".format(it) }
                    
                    if (calculatedHash != expectedHash) {
                        targetFile.delete()
                        throw GradleException("SHA-256 verification failed for downloaded ${filename}!")
                    }
                } catch (e: Exception) {
                    println("Failed to download libmpv.so for ${abi}: \${e.message}")
                    if (targetFile.exists()) targetFile.delete()
                }
            }
        }
    }
}

tasks.configureEach {
    if (name.contains("preBuild") || name.contains("externalNativeBuild")) {
        dependsOn(downloadMpvTask)
    }
}
